image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
    - build
    - test

build:
    stage: build
    script:
        - "dotnet build"
    artifacts:
      paths:
        - bin/
    tag: backend

test:
    stage: test
    script: 
        - "dotnet test"
    tag: backend