version: '3.8'

services:
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    environment:
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    ports: 
      - 5672:5672
      - 5671:5671
      - 15672:15672
    networks:
      rabbitmq-network:
  
  db:
    build:
      context: .
      dockerfile: Data/Dockerfile
    environment:
      - MSSQL_SA_PASSWORD=Dexcelence!1
    networks:
      mssql-network:

  identity:
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile.dev
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=identity;User=sa;Password=Dexcelence!1;
      - App__Self__IssuerUri=https://identity:5005
      - App__Api__DeXApiUrl=https://api:5001
      - ASPNETCORE_URLS=http://+:5004;https://+:5005;
      - ASPNETCORE_HTTPS_PORT=5005
      - ASPNETCORE_Kestrel__Certificates__Default__Password=W64x4AD8dNj9kImdX3tayS
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/dex-identity.pfx
    networks:
      mssql-network:
    ports:
      - 5004:5004
      - 5005:5005
    deploy:
      restart_policy:
        condition: on-failure
  
  notificationservice:
    build:
      context: .
      dockerfile: NotificationSystem/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST_NAME=rabbitmq
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SENDGRID_EMAIL_FROM=${SENDGRID_EMAIL_FROM}
    stdin_open: true
    tty: true
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      rabbitmq-network:

  api:
    build:
      context: .
      dockerfile: API/Dockerfile.dev
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=master;User=sa;Password=Dexcelence!1;
      - App__IdentityServer__IdentityUrl=http://identity:5004
      - ASPNETCORE_URLS=http://+:5000;https://+:5001;
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=xI90DrNea7M6UJFNDwip6t
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/dex-api.pfx
      - RABBITMQ_HOST_NAME=rabbitmq
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    networks:
      mssql-network:
      rabbitmq-network:
    ports:
      - 5000:5000
      - 5001:5001
    deploy:
       restart_policy:
        condition: on-failure

networks:
  mssql-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
  rabbitmq-network:
    driver: bridge
