name: Code Coverage

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Dependencies
      run: dotnet tool install -g dotnet-reportgenerator-globaltool
      
    - name: Build
      run: dotnet build --configuration Release
      
    - name: Test code coverage
      #Threshold = percetage 0-100 | ThresholdType=line/branch/method
      run:  dotnet test
        /p:CollectCoverage=true 
        /p:CoverletOutputFormat=opencover
        /p:Threshold=30
        /p:ThresHoldType=line 
        /p:ThresholdStat=Total 
        /p:CoverletOutput='../TestResults/' 
        /p:ExcludeByFile=\"**/models/**/*.cs%2c**/Microsoft.NET.Test/**/*.cs%2c**/Data/**/*.cs%2c**/3_Repositories.Tests/**/*.cs%2c**/Services.Sources.Resources/**/.cs\"
        /p:MergeWith='../TestResults/coverage.opencover.xml'

    - name: Generate report
      run: reportgenerator 
        "-reports:TestResults/coverage.opencover.xml" 
        "-targetdir:coveragereport" 
        -reporttypes:Html

    - name: Upload report to artifacts
      uses: actions/upload-artifact@v2
      with:
        name: codecov-report
        path: coveragereport/
